services:

  app:
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:${DB_EXTERNAL_PORT}/${DB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - database
    env_file:
      - ../waggle/.env

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      TZ: Asia/Seoul
    ports:
      - '${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: