version: '3.8'

services:

  app:
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_CONTAINER_NAME}:${DB_EXTERNAL_PORT}/${DB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379 
    depends_on:
      - database
      - redis
    env_file:
      - .env
    networks:
      - nginx_waggle_net

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      TZ: Asia/Seoul
    ports:
      - '${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - nginx_waggle_net

  redis:
    image: redis:latest
    ports:
      - '${REDIS_EXTERNAL_PORT}:${REDIS_INTERNAL_PORT}'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - redis-data:/data
    networks:
      - nginx_waggle_net

volumes:
  db-data:
  redis-data:

networks:
  nginx_waggle_net:
    external: true