spring:
  config:
    activate:
      on-profile: prod

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${PROD_HTTPS_FULL_URL}${GOOGLE_REDIRECT_URI}

          kakao:
            redirect-uri: ${PROD_HTTPS_FULL_URL}${KAKAO_REDIRECT_URI}

          naver:
            redirect-uri: ${PROD_HTTPS_FULL_URL}${NAVER_REDIRECT_URI}

server:
  servlet:
    context-path: ${PROD_ENDPOINT}